local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

-- Docker Compose snippets
ls.add_snippets('yaml', {
  -- Basic docker-compose
  s("compose", {
    t({"version: '3.8'",""}),
    t({"",""}),
    t({"services:",""}),
    t({"  app:",""}),
    t({"    build: .",""}),
    t({"    ports:",""}),
    t({"      - \"3000:3000\"",""}),
    t({"    environment:",""}),
    t({"      - NODE_ENV=production",""}),
    t({"    depends_on:",""}),
    t({"      - db",""}),
    t({"",""}),
    t({"  db:",""}),
    t({"    image: postgres:15",""}),
    t({"    environment:",""}),
    t({"      POSTGRES_DB: myapp",""}),
    t({"      POSTGRES_USER: user",""}),
    t({"      POSTGRES_PASSWORD: password",""}),
    t({"    volumes:",""}),
    t({"      - postgres_data:/var/lib/postgresql/data",""}),
    t({"",""}),
    t({"volumes:",""}),
    t({"  postgres_data:",""})
  }),

  -- Web stack
  s("web-stack", {
    t({"version: '3.8'",""}),
    t({"",""}),
    t({"services:",""}),
    t({"  nginx:",""}),
    t({"    image: nginx:alpine",""}),
    t({"    ports:",""}),
    t({"      - \"80:80\"",""}),
    t({"      - \"443:443\"",""}),
    t({"    volumes:",""}),
    t({"      - ./nginx.conf:/etc/nginx/nginx.conf",""}),
    t({"      - ./ssl:/etc/nginx/ssl",""}),
    t({"    depends_on:",""}),
    t({"      - app",""}),
    t({"",""}),
    t({"  app:",""}),
    t({"    build: .",""}),
    t({"    environment:",""}),
    t({"      - NODE_ENV=production",""}),
    t({"    depends_on:",""}),
    t({"      - db",""}),
    t({"      - redis",""}),
    t({"",""}),
    t({"  db:",""}),
    t({"    image: postgres:15",""}),
    t({"    environment:",""}),
    t({"      POSTGRES_DB: myapp",""}),
    t({"      POSTGRES_USER: user",""}),
    t({"      POSTGRES_PASSWORD: password",""}),
    t({"    volumes:",""}),
    t({"      - postgres_data:/var/lib/postgresql/data",""}),
    t({"",""}),
    t({"  redis:",""}),
    t({"    image: redis:7-alpine",""}),
    t({"    volumes:",""}),
    t({"      - redis_data:/data",""}),
    t({"",""}),
    t({"volumes:",""}),
    t({"  postgres_data:",""}),
    t({"  redis_data:",""})
  }),

  -- Development environment
  s("dev-env", {
    t({"version: '3.8'",""}),
    t({"",""}),
    t({"services:",""}),
    t({"  app:",""}),
    t({"    build:",""}),
    t({"      context: .",""}),
    t({"      dockerfile: Dockerfile.dev",""}),
    t({"    ports:",""}),
    t({"      - \"3000:3000\"",""}),
    t({"    volumes:",""}),
    t({"      - .:/app",""}),
    t({"      - /app/node_modules",""}),
    t({"    environment:",""}),
    t({"      - NODE_ENV=development",""}),
    t({"    command: npm run dev",""}),
    t({"",""}),
    t({"  db:",""}),
    t({"    image: postgres:15",""}),
    t({"    ports:",""}),
    t({"      - \"5432:5432\"",""}),
    t({"    environment:",""}),
    t({"      POSTGRES_DB: myapp_dev",""}),
    t({"      POSTGRES_USER: dev",""}),
    t({"      POSTGRES_PASSWORD: dev",""}),
    t({"    volumes:",""}),
    t({"      - postgres_dev_data:/var/lib/postgresql/data",""}),
    t({"",""}),
    t({"volumes:",""}),
    t({"  postgres_dev_data:",""})
  })
})
