local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

-- Terraform Azure Management Group snippet
ls.add_snippets('terraform', {
  s("mg-lua", {
    t({
      'variable "first_hirarchy" {',
      '  description = "First hierarchy management groups."',
      '  type = object({',
      '    parent_id = string',
      '    management_groups = list(object({',
      '      id           = string',
      '      display_name = string',
      '    }))',
      '  })',
      '}',
      '',
      'variable "platform_hirarchy" {',
      '  description = "Platform hierarchy management groups."',
      '  type = object({',
      '    parent_id = string',
      '    management_groups = list(object({',
      '      id           = string',
      '      display_name = string',
      '    }))',
      '  })',
      '}',
      '',
      'variable "landing_zone_hirarchy" {',
      '  description = "Landing zone hierarchy management groups."',
      '  type = object({',
      '    parent_id = string',
      '    management_groups = list(object({',
      '      id           = string',
      '      display_name = string',
      '    }))',
      '  })',
      '}',
      '',
      'resource "azurerm_management_group" "first_hirarchy" {',
      '  for_each                   = { for mg in var.first_hirarchy.management_groups : mg.id => mg }',
      '  name                       = each.value.id',
      '  display_name               = each.value.display_name',
      '  parent_management_group_id = var.first_hirarchy.parent_id',
      '}',
      '',
      'resource "azurerm_management_group" "platform_hirarchy" {',
      '  for_each                   = { for mg in var.platform_hirarchy.management_groups : mg.id => mg }',
      '  name                       = each.value.id',
      '  display_name               = each.value.display_name',
      '  parent_management_group_id = var.platform_hirarchy.parent_id',
      '  depends_on                 = [azurerm_management_group.first_hirarchy]',
      '}',
      '',
      'resource "azurerm_management_group" "landing_zone_hirarchy" {',
      '  for_each                   = { for mg in var.landing_zone_hirarchy.management_groups : mg.id => mg }',
      '  name                       = each.value.id',
      '  display_name               = each.value.display_name',
      '  parent_management_group_id = var.landing_zone_hirarchy.parent_id',
      '  depends_on                 = [azurerm_management_group.first_hirarchy]',
      '}',
      '',
      'output "first_hirarchy_ids" {',
      '  description = "IDs of the first hierarchy management groups."',
      '  value       = azurerm_management_group.first_hirarchy',
      '}',
      '',
      'output "platform_hirarchy_ids" {',
      '  description = "IDs of the platform hierarchy management groups."',
      '  value       = azurerm_management_group.platform_hirarchy',
      '}',
      '',
      'output "landing_zone_hirarchy_ids" {',
      '  description = "IDs of the landing zone hierarchy management groups."',
      '  value       = azurerm_management_group.landing_zone_hirarchy',
      '}',
    }),
  }),
})

-- Management Group JSON data snippet
ls.add_snippets('json', {
  s("mg-json-lua", {
    t({
      '{',
      '  "first_hirarchy": {',
      '    "parent_id": "plb",',
      '    "management_groups": [',
      '      {',
      '        "id": "plb-platform",',
      '        "display_name": "Platform"',
      '      },',
      '      {',
      '        "id": "plb-landing-zones",',
      '        "display_name": "Landing Zones"',
      '      },',
      '      {',
      '        "id": "plb-decommissioned",',
      '        "display_name": "Decommissioned"',
      '      },',
      '      {',
      '        "id": "plb-sandbox",',
      '        "display_name": "Sandbox"',
      '      }',
      '    ]',
      '  },',
      '  "platform_hirarchy": {',
      '    "parent_id": "plb-platform",',
      '    "management_groups": [',
      '      {',
      '        "id": "plb-platform-security",',
      '        "display_name": "Security"',
      '      },',
      '      {',
      '        "id": "plb-platform-management",',
      '        "display_name": "Management"',
      '      },',
      '      {',
      '        "id": "plb-platform-identity",',
      '        "display_name": "Identity"',
      '      },',
      '      {',
      '        "id": "plb-platform-connectivity",',
      '        "display_name": "Connectivity"',
      '      }',
      '    ]',
      '  },',
      '  "landing_zone_hirarchy": {',
      '    "parent_id": "plb-landing-zones",',
      '    "management_groups": [',
      '      {',
      '        "id": "plb-landing-zones-corp",',
      '        "display_name": "Corp"',
      '      },',
      '      {',
      '        "id": "plb-landing-zones-online",',
      '        "display_name": "Online"',
      '      }',
      '    ]',
      '  }',
      '}',
    }),
  }),
  s("mg-json-canary-lua", {
    t({
      '{',
      '  "first_hirarchy": {',
      '    "parent_id": "plb-canary",',
      '    "management_groups": [',
      '      {',
      '        "id": "platform-canary",',
      '        "display_name": "Platform - Canary"',
      '      },',
      '      {',
      '        "id": "landing-zones-canary",',
      '        "display_name": "Landing Zones - Canary"',
      '      },',
      '      {',
      '        "id": "decommissioned-canary",',
      '        "display_name": "Decommissioned - Canary"',
      '      },',
      '      {',
      '        "id": "sandbox-canary",',
      '        "display_name": "Sandbox - Canary"',
      '      }',
      '    ]',
      '  },',
      '  "platform_hirarchy": {',
      '    "parent_id": "platform-canary",',
      '    "management_groups": [',
      '      {',
      '        "id": "platform-security-canary",',
      '        "display_name": "Security - Canary"',
      '      },',
      '      {',
      '        "id": "platform-management-canary",',
      '        "display_name": "Management - Canary"',
      '      },',
      '      {',
      '        "id": "platform-identity-canary",',
      '        "display_name": "Identity - Canary"',
      '      },',
      '      {',
      '        "id": "platform-connectivity-canary",',
      '        "display_name": "Connectivity - Canary"',
      '      }',
      '    ]',
      '  },',
      '  "landing_zone_hirarchy": {',
      '    "parent_id": "landing-zones-canary",',
      '    "management_groups": [',
      '      {',
      '        "id": "landing-zones-corp-canary",',
      '        "display_name": "Corp - Canary"',
      '      },',
      '      {',
      '        "id": "landing-zones-online-canary",',
      '        "display_name": "Online - Canary"',
      '      }',
      '    ]',
      '  }',
      '}',
    }),
  }),
})

