name: pipelineName

trigger:
  branches:
    include:
    - main
    - releases/*
    - feature/*
    exclude:
    - releases/old*
    - feature/*-working
  paths:
    include:
    - docs
    exclude:
    - docs/README.md
  tags:
    include:
    - v2.*
    exclude:
    - v2.0

pool:
  name: selfhosted
