local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local c = ls.choice_node
local i = ls.insert_node
local f = ls.function_node

-- Import common utilities
local utils = require("snippets.utils")
local fn = utils.fn

-- Azure Pipelines snippets
ls.add_snippets('yaml', {
  s("trigger", {
    t({"trigger:"}),
    t({"", "  branches:"}),
    t({"", "    include:"}),
    t({"", "    - main"}),
    t({"", "  paths:"}),
    t({"", "    include:"}),
    t({"", "    - path/**"}),
    t({"", ""}),
    t({"", "pool: 'selfhosted'"}),
    t({"", ""}),
    t({"", "stages:"}),
    t({"", "- stage: "}), i(1, "stage_name"),
    t({"", "  displayName: "}), i(2, "stage_name"),
    t({"", "  jobs:"}),
    t({"", "  - job: "}), i(3, "job_name"),
    t({"", "    displayName: "}), i(4, "job_name"),
    t({"", "    steps: "}),
    t({"", "    - script: echo \"Hello World\""}),
    t({"", "      displayName: \"Print Hello World\""}),
    t({"", ""}),
    i(0, ""),
  }),
  s("stage", {
    t({"stages:"}),
    t({"", "- stage: "}), i(1, "stage_name"),
    t({"", "  displayName: "}), i(2, "stage_name"),
    t({"", "  jobs:"}),
    t({"", "  - job: "}), i(3, "job_name"),
    t({"", "    displayName: "}), i(4, "job_name"),
    t({"", "    steps: "}),
    t({"", "    - script: echo \"Hello World\""}),
    t({"", "      displayName: \"Print Hello World\""}),
    t({"", ""}),
    i(0, ""),
  }),
  s("step-bash", {
    t({"    steps: "}),
    t({"", "    - script: "}), i(1, "echo \"Hello World\""),
    t({"", "      displayName: \""}), i(2, "step-bash"), t({"\""}),
    t({"", ""}),
    i(0, ""),
  }),
  s("step-pwsh", {
    t({"    steps: "}),
    t({"", "    - task: azurepowershell@5"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: '"}), i(1, "serviceConnection"), t({"'"}),
    t({"", "        scriptType: 'inlinescript' # 'filepath'"}),
    t({"", "        #scriptPath: '/script.ps1'"}),
    t({"", "        inline: |"}),
    t({"", "          echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        #scriptArguments: '-param1 value1 -param2 value2'"}),
    t({"", "        errorActionPreference: 'stop' # 'continue' | 'silentlycontinue'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "        azurePowerShellVersion:  'latestversion' # 'otherversion'"}),
    t({"", "        #preferredAzurePowerShellVersion: '7.1.0'"}),
    t({"", "        pwsh: true"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "      displayName: '"}), i(2, "task displayname"), t({"'"}),
    t({"", ""}),
    i(0, ""),
  }),
  s("step-pwsh-sub-deploy", {
    t({"    steps: "}),
    t({"", "    - task: AzurePowerShell@5"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: '"}), i(1, "mi-platform-plz-sub-wi-nonprod-001"), t({"'"}),
    t({"", "        ScriptType: 'InlineScript' # 'FilePath'"}),
    t({"", "        #ScriptPath: '/script.ps1'"}),
    t({"", "        Inline: |"}),
    t({"", "          # deploy on mg scope"}),
    t({"", "          $response = ("}),
    t({"", "             new-AzManagementGroupDeploymentStack `"}),
    t({"", "                -Name \""}), i(2, "platform-sub-stack"), t({"\" `"}),
    t({"", "                -ManagementGroupId \""}), i(3, "plbtf-platform"), t({"\" `"}),
    t({"", "                -Location \""}), i(4, "West India"), t({"\" `"}),
    t({"", "                -TemplateParameterFile \"$(System.DefaultWorkingDirectory)/landingZones/tf/params/platform/nonprod.bicepparam\" `"}),
    t({"", "                -ActionOnUnManage 'DeleteAll' `"}),
    t({"", "                -DenySettingsMode 'None' `"}),
    t({"", "                -Force"}),
    t({"", "                )"}),
    t({"", "                # -ActionOnUnManage 'DetachAll' ` # | DeleteResources | DeleteAll"}),
    t({"", "                # -DenySettingsMode 'None' ` # | DenyDelete | DenyWriteAndDelete `"}),
    t({"", "                "}),
    t({"", "          write-output '------- Outputs -------'"}),
    t({"", "          $subscriptionId = $response.Outputs.subscriptionId.Value"}),
    t({"", "          write-output 'subscriptionId: ' $subscriptionId"}),
    t({"", "          echo \"##vso[task.setvariable variable=subscriptionId;isoutput=true]$subscriptionId\""}),
    t({"", ""}),
    t({"", "          write-output '------- Response -------'"}),
    t({"", "          $response"}),
    t({"", ""}),
    t({"", "        #ScriptArguments: '-param1 value1 -param2 value2'"}),
    t({"", "        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'"}),
    t({"", "        FailOnStandardError: false"}),
    t({"", "        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'"}),
    t({"", "        #preferredAzurePowerShellVersion: '7.1.0'"}),
    t({"", "        pwsh: true"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "      name: '"}), i(5, "sub_deploy"), t({"'"}),
    t({"", "      displayName: '"}), i(6, "sub_deploy"), t({"'"}),
    t({"", ""}),
    i(0, ""),
  }),
  s("ado-variables", {
    t({"variables:", ""}),
    t({"  - name: variableKey", ""}),
    t({"    value: 'variableValue'", ""})
  }),
  s("variables-multi", {
    t({"variables:"}),
    t({"", "  "}), i(1, "key"), t({":"}),
    t({"", "    - "}), i(2, "value1"),
    t({"", "    - "}), i(3, "value2"),
    t({"", "    - "}), i(4, "value3"),
    t({"", ""}),
    i(0, ""),
  })
})
