local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

-- Azure Pipelines stages snippet with AzureCLI@2 tasks
ls.add_snippets('yaml', {
  s("stages-lua", {
    t({"stages:"}),
    t({"", "- stage: "}), i(1, "stage_name"),
    t({"", "  displayName: "}), i(2, "stage_name"),
    t({"", "  jobs:"}),
    t({"", "  - job: "}), i(3, "job_name"),
    t({"", "    displayName: "}), i(4, "job_name"),
    t({"", ""}),
    t({"", "    steps: "}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionDev)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "              echo \"Dev Deployment\""}),
    t({"", "              echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionTest)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "              echo \"Test Deployment\""}),
    t({"", "              echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionProd)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "              echo \"Prod Deployment\""}),
    t({"", "              echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    i(0, ""),
  }),
})
