local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

-- Azure Pipelines trigger snippet with PowerShell tasks
ls.add_snippets('yaml', {
  s("trigger-pwsh-full-lua", {
    t({"trigger:"}),
    t({"", "  branches:"}),
    t({"", "    include:"}),
    t({"", "    - main"}),
    t({"", "  paths:"}),
    t({"", "    include:"}),
    t({"", "    - path/**"}),
    t({"", "  batch: true"}),
    t({"", ""}),
    t({"", "variables:"}),
    t({"", "  serviceConnectionDev: 'id-policy-vending-eus-dev-001'"}),
    t({"", "  serviceConnectionTest: 'id-policy-vending-eus-test-001'"}),
    t({"", "  serviceConnectionProd: 'id-policy-vending-eus-prod-001'"}),
    t({"", ""}),
    t({"", "pool: 'default'"}),
    t({"", ""}),
    t({"", "stages:"}),
    t({"", "- stage: Dev"}),
    t({"", "  displayName: Dev"}),
    t({"", "  jobs:"}),
    t({"", "  - job: DevJob"}),
    t({"", "    displayName: DevJob"}),
    t({"", ""}),
    t({"", "    steps: "}),
    t({"", "    - task: azurepowershell@5"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionDev)"}),
    t({"", "        scriptType: 'inlinescript' # 'filepath'"}),
    t({"", "        #scriptPath: '/script.ps1'"}),
    t({"", "        inline: |"}),
    t({"", "          echo \"Dev Deployment\""}),
    t({"", "          echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        #scriptArguments: '-param1 value1 -param2 value2'"}),
    t({"", "        errorActionPreference: 'stop' # 'continue' | 'silentlycontinue'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "        azurePowerShellVersion:  'latestversion' # 'otherversion'"}),
    t({"", "        #preferredAzurePowerShellVersion: '7.1.0'"}),
    t({"", "        pwsh: true"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    t({"", "- stage: Test"}),
    t({"", "  displayName: Test"}),
    t({"", "  jobs:"}),
    t({"", "  - job: TestJob"}),
    t({"", "    displayName: TestJob"}),
    t({"", ""}),
    t({"", "    steps: "}),
    t({"", "    - task: azurepowershell@5"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionTest)"}),
    t({"", "        scriptType: 'inlinescript' # 'filepath'"}),
    t({"", "        #scriptPath: '/script.ps1'"}),
    t({"", "        inline: |"}),
    t({"", "          echo \"Test Deployment\""}),
    t({"", "          echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        #scriptArguments: '-param1 value1 -param2 value2'"}),
    t({"", "        errorActionPreference: 'stop' # 'continue' | 'silentlycontinue'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "        azurePowerShellVersion:  'latestversion' # 'otherversion'"}),
    t({"", "        #preferredAzurePowerShellVersion: '7.1.0'"}),
    t({"", "        pwsh: true"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    t({"", "- stage: Prod"}),
    t({"", "  displayName: Prod"}),
    t({"", "  jobs:"}),
    t({"", "  - job: ProdJob"}),
    t({"", "    displayName: ProdJob"}),
    t({"", ""}),
    t({"", "    steps: "}),
    t({"", ""}),
    t({"", "    - task: azurepowershell@5"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionProd)"}),
    t({"", "        scriptType: 'inlinescript' # 'filepath'"}),
    t({"", "        #scriptPath: '/script.ps1'"}),
    t({"", "        inline: |"}),
    t({"", "          echo \"Prod Deployment\""}),
    t({"", "          echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        #scriptArguments: '-param1 value1 -param2 value2'"}),
    t({"", "        errorActionPreference: 'stop' # 'continue' | 'silentlycontinue'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "        azurePowerShellVersion:  'latestversion' # 'otherversion'"}),
    t({"", "        #preferredAzurePowerShellVersion: '7.1.0'"}),
    t({"", "        pwsh: true"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
  }),
})

