local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

-- Azure Pipelines trigger snippet with CLI tasks
ls.add_snippets('yaml', {
  s("trigger-cli-full-lua", {
    t({"trigger:"}),
    t({"", "  branches:"}),
    t({"", "    include:"}),
    t({"", "    - main"}),
    t({"", "  paths:"}),
    t({"", "    include:"}),
    t({"", "    - mgmt-group/**"}),
    t({"", "  batch: true"}),
    t({"", ""}),
    t({"", "variables:"}),
    t({"", "  serviceConnectionNonProd: 'id-platform-vending-eus-nonprod-001'"}),
    t({"", "  serviceConnectionProd: 'id-platform-vending-eus-prod-001'"}),
    t({"", "  subscriptionIdNonProd: '0baa6eee-3e96-4821-b9bb-9ba4e9cd2dc8'"}),
    t({"", "  subscriptionIdProd: 'e8d0f9e9-2ea9-4973-99d6-f464cdb35bf3'"}),
    t({"", "  "}),
    t({"", "  # Backend configuration for Canary (NonProd)"}),
    t({"", "  backendResourceGroupNonProd: 'rg-platform-tf-eus-nonprod-001'"}),
    t({"", "  backendStorageAccountNonProd: 'sttfstateeusnonprod001'"}),
    t({"", "  backendContainerName: 'tfstate'"}),
    t({"", "  backendKeyCanary: 'mgmt.group.canary.tfstate'"}),
    t({"", "  "}),
    t({"", "  # Backend configuration for PLB (Prod)"}),
    t({"", "  backendResourceGroupProd: 'rg-platform-tf-eus-prod-001'"}),
    t({"", "  backendStorageAccountProd: 'sttfstateeusprod001'"}),
    t({"", "  backendKeyPlb: 'mgmt.group.plb.tfstate'"}),
    t({"", ""}),
    t({"", "pool: 'default'"}),
    t({"", ""}),
    t({"", "stages:"}),
    t({"", "# ============================================"}),
    t({"", "# NonProd (Canary) Environment Stages"}),
    t({"", "# ============================================"}),
    t({"", "- stage: PlanCanary"}),
    t({"", "  displayName: 'Plan - Canary (NonProd)'"}),
    t({"", "  jobs:"}),
    t({"", "  - job: PlanCanaryManagementGroups"}),
    t({"", "    displayName: 'Plan Management Groups - Canary'"}),
    t({"", "    steps: "}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionNonProd)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "            az account set --subscription $(subscriptionIdNonProd)"}),
    t({"", "            cd mgmt-group"}),
    t({"", ""}),
    t({"", "            # Get Azure context and set ARM variables for Azure provider authentication"}),
    t({"", "            SUBSCRIPTION_ID=$(az account show --query id -o tsv)"}),
    t({"", "            TENANT_ID=$(az account show --query tenantId -o tsv)"}),
    t({"", "            CLIENT_ID=$(az account show --query user.name -o tsv)"}),
    t({"", ""}),
    t({"", "            # Set ARM environment variables for Terraform Azure provider"}),
    t({"", "            export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID"}),
    t({"", "            export ARM_TENANT_ID=$TENANT_ID"}),
    t({"", "            export ARM_CLIENT_ID=$CLIENT_ID"}),
    t({"", "            export ARM_USE_OIDC=true"}),
    t({"", ""}),
    t({"", "            # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI"}),
    t({"", "            unset AZURE_CONFIG_DIR"}),
    t({"", "            "}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"Terraform Plan - Canary Environment\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID\""}),
    t({"", "            echo \"ARM_TENANT_ID: $ARM_TENANT_ID\""}),
    t({"", "            echo \"ARM_CLIENT_ID: $CLIENT_ID\""}),
    t({"", "            echo \"ARM_USE_OIDC: $ARM_USE_OIDC\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", ""}),
    t({"", "            terraform init \\"}),
    t({"", "              -backend-config=\"resource_group_name=$(backendResourceGroupNonProd)\" \\"}),
    t({"", "              -backend-config=\"storage_account_name=$(backendStorageAccountNonProd)\" \\"}),
    t({"", "              -backend-config=\"container_name=$(backendContainerName)\" \\"}),
    t({"", "              -backend-config=\"key=$(backendKeyCanary)\" \\"}),
    t({"", "              -var-file=canary.tfvars.json"}),
    t({"", ""}),
    t({"", "            terraform plan -var-file=canary.tfvars.json -out=tfplan-canary"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: true"}),
    t({"", "        displayName: 'Terraform Plan - Canary'"}),
    t({"", ""}),
    t({"", "- stage: DeployCanary"}),
    t({"", "  displayName: 'Deploy - Canary (NonProd)'"}),
    t({"", "  dependsOn: PlanCanary"}),
    t({"", "  condition: succeeded()"}),
    t({"", "  jobs:"}),
    t({"", "  - job: DeployCanaryManagementGroups"}),
    t({"", "    displayName: 'Deploy Management Groups - Canary'"}),
    t({"", "    steps:"}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionNonProd)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "            az account set --subscription $(subscriptionIdNonProd)"}),
    t({"", "            cd mgmt-group"}),
    t({"", ""}),
    t({"", "            # Get Azure context and set ARM variables for Azure provider authentication"}),
    t({"", "            SUBSCRIPTION_ID=$(az account show --query id -o tsv)"}),
    t({"", "            TENANT_ID=$(az account show --query tenantId -o tsv)"}),
    t({"", "            CLIENT_ID=$(az account show --query user.name -o tsv)"}),
    t({"", ""}),
    t({"", "            # Set ARM environment variables for Terraform Azure provider"}),
    t({"", "            export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID"}),
    t({"", "            export ARM_TENANT_ID=$TENANT_ID"}),
    t({"", "            export ARM_CLIENT_ID=$CLIENT_ID"}),
    t({"", "            export ARM_USE_OIDC=true"}),
    t({"", ""}),
    t({"", "            # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI"}),
    t({"", "            unset AZURE_CONFIG_DIR"}),
    t({"", "            "}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"Terraform Apply - Canary Environment\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID\""}),
    t({"", "            echo \"ARM_TENANT_ID: $ARM_TENANT_ID\""}),
    t({"", "            echo \"ARM_CLIENT_ID: $CLIENT_ID\""}),
    t({"", "            echo \"ARM_USE_OIDC: $ARM_USE_OIDC\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", ""}),
    t({"", "            terraform init \\"}),
    t({"", "              -backend-config=\"resource_group_name=$(backendResourceGroupNonProd)\" \\"}),
    t({"", "              -backend-config=\"storage_account_name=$(backendStorageAccountNonProd)\" \\"}),
    t({"", "              -backend-config=\"container_name=$(backendContainerName)\" \\"}),
    t({"", "              -backend-config=\"key=$(backendKeyCanary)\" \\"}),
    t({"", "              -var-file=canary.tfvars.json"}),
    t({"", ""}),
    t({"", "            terraform apply -auto-approve -var-file=canary.tfvars.json -parallelism=50"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: true"}),
    t({"", "        displayName: 'Terraform Apply - Canary'"}),
    t({"", ""}),
    t({"", "# ============================================"}),
    t({"", "# Prod (PLB) Environment Stages"}),
    t({"", "# ============================================"}),
    t({"", "- stage: PlanProd"}),
    t({"", "  displayName: 'Plan - PLB (Prod)'"}),
    t({"", "  dependsOn: DeployCanary"}),
    t({"", "  condition: succeeded()"}),
    t({"", "  jobs:"}),
    t({"", "  - job: PlanProdManagementGroups"}),
    t({"", "    displayName: 'Plan Management Groups - PLB'"}),
    t({"", "    steps:"}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionProd)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "            az account set --subscription $(subscriptionIdProd)"}),
    t({"", "            cd mgmt-group"}),
    t({"", ""}),
    t({"", "            # Get Azure context and set ARM variables for Azure provider authentication"}),
    t({"", "            SUBSCRIPTION_ID=$(az account show --query id -o tsv)"}),
    t({"", "            TENANT_ID=$(az account show --query tenantId -o tsv)"}),
    t({"", "            CLIENT_ID=$(az account show --query user.name -o tsv)"}),
    t({"", ""}),
    t({"", "            # Set ARM environment variables for Terraform Azure provider"}),
    t({"", "            export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID"}),
    t({"", "            export ARM_TENANT_ID=$TENANT_ID"}),
    t({"", "            export ARM_CLIENT_ID=$CLIENT_ID"}),
    t({"", "            export ARM_USE_OIDC=true"}),
    t({"", ""}),
    t({"", "            # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI"}),
    t({"", "            unset AZURE_CONFIG_DIR"}),
    t({"", "            "}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"Terraform Plan - PLB Production Environment\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID\""}),
    t({"", "            echo \"ARM_TENANT_ID: $ARM_TENANT_ID\""}),
    t({"", "            echo \"ARM_CLIENT_ID: $CLIENT_ID\""}),
    t({"", "            echo \"ARM_USE_OIDC: $ARM_USE_OIDC\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", ""}),
    t({"", "            terraform init \\"}),
    t({"", "              -backend-config=\"resource_group_name=$(backendResourceGroupProd)\" \\"}),
    t({"", "              -backend-config=\"storage_account_name=$(backendStorageAccountProd)\" \\"}),
    t({"", "              -backend-config=\"container_name=$(backendContainerName)\" \\"}),
    t({"", "              -backend-config=\"key=$(backendKeyPlb)\" \\"}),
    t({"", "              -var-file=plb.tfvars.json"}),
    t({"", ""}),
    t({"", "            terraform plan -var-file=plb.tfvars.json -out=tfplan-plb"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: true"}),
    t({"", "        displayName: 'Terraform Plan - PLB'"}),
    t({"", ""}),
    t({"", "- stage: DeployProd"}),
    t({"", "  displayName: 'Deploy - PLB (Prod)'"}),
    t({"", "  dependsOn: PlanProd"}),
    t({"", "  condition: succeeded()"}),
    t({"", "  jobs:"}),
    t({"", "  - job: DeployProdManagementGroups"}),
    t({"", "    displayName: 'Deploy Management Groups - PLB'"}),
    t({"", "    steps:"}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionProd)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "            az account set --subscription $(subscriptionIdProd)"}),
    t({"", "            cd mgmt-group"}),
    t({"", ""}),
    t({"", "            # Get Azure context and set ARM variables for Azure provider authentication"}),
    t({"", "            SUBSCRIPTION_ID=$(az account show --query id -o tsv)"}),
    t({"", "            TENANT_ID=$(az account show --query tenantId -o tsv)"}),
    t({"", "            CLIENT_ID=$(az account show --query user.name -o tsv)"}),
    t({"", ""}),
    t({"", "            # Set ARM environment variables for Terraform Azure provider"}),
    t({"", "            export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID"}),
    t({"", "            export ARM_TENANT_ID=$TENANT_ID"}),
    t({"", "            export ARM_CLIENT_ID=$CLIENT_ID"}),
    t({"", "            export ARM_USE_OIDC=true"}),
    t({"", ""}),
    t({"", "            # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI"}),
    t({"", "            unset AZURE_CONFIG_DIR"}),
    t({"", "            "}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"Terraform Apply - PLB Production Environment\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID\""}),
    t({"", "            echo \"ARM_TENANT_ID: $ARM_TENANT_ID\""}),
    t({"", "            echo \"ARM_CLIENT_ID: $CLIENT_ID\""}),
    t({"", "            echo \"ARM_USE_OIDC: $ARM_USE_OIDC\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", ""}),
    t({"", "            terraform init \\"}),
    t({"", "              -backend-config=\"resource_group_name=$(backendResourceGroupProd)\" \\"}),
    t({"", "              -backend-config=\"storage_account_name=$(backendStorageAccountProd)\" \\"}),
    t({"", "              -backend-config=\"container_name=$(backendContainerName)\" \\"}),
    t({"", "              -backend-config=\"key=$(backendKeyPlb)\" \\"}),
    t({"", "              -var-file=plb.tfvars.json"}),
    t({"", ""}),
    t({"", "            terraform apply -auto-approve -var-file=plb.tfvars.json -parallelism=50"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: true"}),
    t({"", "        displayName: 'Terraform Apply - PLB'"}),
    t({"", ""}),
  }),
})
