local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

-- Azure Pipelines trigger snippet
ls.add_snippets('yaml', {
  s("ado-trigger-cli-full", {
    t({"trigger:"}),
    t({"", "  branches:"}),
    t({"", "    include:"}),
    t({"", "    - main"}),
    t({"", "  paths:"}),
    t({"", "    include:"}),
    t({"", "    - path/**"}),
    t({"", "  batch: true"}),
    t({"", ""}),
    t({"", "variables:"}),
    t({"", "  serviceConnectionDev: 'id-<resource>-vending-eus-dev-001'"}),
    t({"", "  serviceConnectionTest: 'id-<resource>-vending-eus-test-001'"}),
    t({"", "  serviceConnectionProd: 'id-<resource>-vending-eus-prod-001'"}),
    t({"", ""}),
    t({"", "pool: 'selfhosted'"}),
    t({"", ""}),
    t({"", "stages:"}),
    t({"", "- stage: stage_name"}),
    t({"", "  displayName: stage_name"}),
    t({"", "  jobs:"}),
    t({"", "  - job: job_name"}),
    t({"", "    displayName: job_name"}),
    t({"", ""}),
    t({"", "    steps: "}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: '${serviceConnectionDev}'"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "              echo \"Dev Deployment\""}),
    t({"", "              echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: '${serviceConnectionTest}'"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "              echo \"Test Deployment\""}),
    t({"", "              echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: '${serviceConnectionProd}'"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "              echo \"Prod Deployment\""}),
    t({"", "              echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
  }),
})

