-- -- Debug file to test Bicep snippet loading
-- local ls = require("luasnip")
--
-- -- Simple test snippet
-- ls.add_snippets('bicep', {
--   ls.snippet("test", {
--     ls.text_node("-- This is a test snippet for Bicep"),
--     ls.text_node({"", "param testParam string = 'test'"}),
--   }),
--   
--   ls.snippet("param-simple", {
--     ls.text_node("@description('"),
--     ls.insert_node(1, "Parameter description"),
--     ls.text_node("')"),
--     ls.text_node({"", "param "}),
--     ls.insert_node(2, "parameterName"),
--     ls.text_node(" string = '"),
--     ls.insert_node(3, "defaultValue"),
--     ls.text_node("'"),
--   }),
-- })
--
-- -- Bicep debug snippets loaded
