local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

-- ============================================================================
-- AZURE DEVOPS PIPELINES SNIPPETS (YAML)
-- ============================================================================

ls.add_snippets('yaml', {
  -- Pool snippet
  s("pool-lua", {
    t({"pool: 'selfhosted' # 'default'"}),
    t({"", ""}),
  }),

  -- Variables snippet
  s("variables-lua", {
    t({"variables:"}),
    t({"", "  serviceConnectionDev: 'id-<resource>-vending-eus-dev-001'"}),
    t({"", "  serviceConnectionTest: 'id-<resource>-vending-eus-test-001'"}),
    t({"", "  serviceConnectionProd: 'id-<resource>-vending-eus-prod-001'"}),
    t({"", "  subscriptionIdDev: '<your-dev-subscription-id>'"}),
    t({"", "  subscriptionIdTest: '<your-test-subscription-id>'"}),
    t({"", "  subscriptionIdProd: '<your-prod-subscription-id>'"}),
    t({"", ""}),
  }),

  -- Trigger snippet (basic)
  s("trigger-lua", {
    t({"trigger:"}),
    t({"", "  branches:"}),
    t({"", "    include:"}),
    t({"", "    - main"}),
    t({"", "  paths:"}),
    t({"", "    include:"}),
    t({"", "    - path/**"}),
    t({"", "  batch: true"}),
    t({"", ""}),
  }),

  -- Trigger snippet with CLI tasks (full pipeline)
  s("trigger-cli-full-lua", {
    t({"trigger:"}),
    t({"", "  branches:"}),
    t({"", "    include:"}),
    t({"", "    - main"}),
    t({"", "  paths:"}),
    t({"", "    include:"}),
    t({"", "    - mgmt-group/**"}),
    t({"", "  batch: true"}),
    t({"", ""}),
    t({"", "variables:"}),
    t({"", "  serviceConnectionNonProd: 'id-platform-vending-eus-nonprod-001'"}),
    t({"", "  serviceConnectionProd: 'id-platform-vending-eus-prod-001'"}),
    t({"", "  subscriptionIdNonProd: '0baa6eee-3e96-4821-b9bb-9ba4e9cd2dc8'"}),
    t({"", "  subscriptionIdProd: 'e8d0f9e9-2ea9-4973-99d6-f464cdb35bf3'"}),
    t({"", "  "}),
    t({"", "  # Backend configuration for Canary (NonProd)"}),
    t({"", "  backendResourceGroupNonProd: 'rg-platform-tf-eus-nonprod-001'"}),
    t({"", "  backendStorageAccountNonProd: 'sttfstateeusnonprod001'"}),
    t({"", "  backendContainerName: 'tfstate'"}),
    t({"", "  backendKeyCanary: 'mgmt.group.canary.tfstate'"}),
    t({"", "  "}),
    t({"", "  # Backend configuration for PLB (Prod)"}),
    t({"", "  backendResourceGroupProd: 'rg-platform-tf-eus-prod-001'"}),
    t({"", "  backendStorageAccountProd: 'sttfstateeusprod001'"}),
    t({"", "  backendKeyPlb: 'mgmt.group.plb.tfstate'"}),
    t({"", ""}),
    t({"", "pool: 'default'"}),
    t({"", ""}),
    t({"", "stages:"}),
    t({"", "# ============================================"}),
    t({"", "# NonProd (Canary) Environment Stages"}),
    t({"", "# ============================================"}),
    t({"", "- stage: PlanCanary"}),
    t({"", "  displayName: 'Plan - Canary (NonProd)'"}),
    t({"", "  jobs:"}),
    t({"", "  - job: PlanCanaryManagementGroups"}),
    t({"", "    displayName: 'Plan Management Groups - Canary'"}),
    t({"", "    steps: "}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionNonProd)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "            az account set --subscription $(subscriptionIdNonProd)"}),
    t({"", "            cd mgmt-group"}),
    t({"", ""}),
    t({"", "            # Get Azure context and set ARM variables for Azure provider authentication"}),
    t({"", "            SUBSCRIPTION_ID=$(az account show --query id -o tsv)"}),
    t({"", "            TENANT_ID=$(az account show --query tenantId -o tsv)"}),
    t({"", "            CLIENT_ID=$(az account show --query user.name -o tsv)"}),
    t({"", ""}),
    t({"", "            # Set ARM environment variables for Terraform Azure provider"}),
    t({"", "            export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID"}),
    t({"", "            export ARM_TENANT_ID=$TENANT_ID"}),
    t({"", "            export ARM_CLIENT_ID=$CLIENT_ID"}),
    t({"", "            export ARM_USE_OIDC=true"}),
    t({"", ""}),
    t({"", "            # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI"}),
    t({"", "            unset AZURE_CONFIG_DIR"}),
    t({"", "            "}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"Terraform Plan - Canary Environment\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID\""}),
    t({"", "            echo \"ARM_TENANT_ID: $ARM_TENANT_ID\""}),
    t({"", "            echo \"ARM_CLIENT_ID: $CLIENT_ID\""}),
    t({"", "            echo \"ARM_USE_OIDC: $ARM_USE_OIDC\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", ""}),
    t({"", "            terraform init \\"}),
    t({"", "              -backend-config=\"resource_group_name=$(backendResourceGroupNonProd)\" \\"}),
    t({"", "              -backend-config=\"storage_account_name=$(backendStorageAccountNonProd)\" \\"}),
    t({"", "              -backend-config=\"container_name=$(backendContainerName)\" \\"}),
    t({"", "              -backend-config=\"key=$(backendKeyCanary)\" \\"}),
    t({"", "              -var-file=canary.tfvars.json"}),
    t({"", ""}),
    t({"", "            terraform plan -var-file=canary.tfvars.json -out=tfplan-canary"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: true"}),
    t({"", "        displayName: 'Terraform Plan - Canary'"}),
    t({"", ""}),
    t({"", "- stage: DeployCanary"}),
    t({"", "  displayName: 'Deploy - Canary (NonProd)'"}),
    t({"", "  dependsOn: PlanCanary"}),
    t({"", "  condition: succeeded()"}),
    t({"", "  jobs:"}),
    t({"", "  - job: DeployCanaryManagementGroups"}),
    t({"", "    displayName: 'Deploy Management Groups - Canary'"}),
    t({"", "    steps:"}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionNonProd)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "            az account set --subscription $(subscriptionIdNonProd)"}),
    t({"", "            cd mgmt-group"}),
    t({"", ""}),
    t({"", "            # Get Azure context and set ARM variables for Azure provider authentication"}),
    t({"", "            SUBSCRIPTION_ID=$(az account show --query id -o tsv)"}),
    t({"", "            TENANT_ID=$(az account show --query tenantId -o tsv)"}),
    t({"", "            CLIENT_ID=$(az account show --query user.name -o tsv)"}),
    t({"", ""}),
    t({"", "            # Set ARM environment variables for Terraform Azure provider"}),
    t({"", "            export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID"}),
    t({"", "            export ARM_TENANT_ID=$TENANT_ID"}),
    t({"", "            export ARM_CLIENT_ID=$CLIENT_ID"}),
    t({"", "            export ARM_USE_OIDC=true"}),
    t({"", ""}),
    t({"", "            # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI"}),
    t({"", "            unset AZURE_CONFIG_DIR"}),
    t({"", "            "}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"Terraform Apply - Canary Environment\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID\""}),
    t({"", "            echo \"ARM_TENANT_ID: $ARM_TENANT_ID\""}),
    t({"", "            echo \"ARM_CLIENT_ID: $CLIENT_ID\""}),
    t({"", "            echo \"ARM_USE_OIDC: $ARM_USE_OIDC\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", ""}),
    t({"", "            terraform init \\"}),
    t({"", "              -backend-config=\"resource_group_name=$(backendResourceGroupNonProd)\" \\"}),
    t({"", "              -backend-config=\"storage_account_name=$(backendStorageAccountNonProd)\" \\"}),
    t({"", "              -backend-config=\"container_name=$(backendContainerName)\" \\"}),
    t({"", "              -backend-config=\"key=$(backendKeyCanary)\" \\"}),
    t({"", "              -var-file=canary.tfvars.json"}),
    t({"", ""}),
    t({"", "            terraform apply -auto-approve -var-file=canary.tfvars.json -parallelism=50"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: true"}),
    t({"", "        displayName: 'Terraform Apply - Canary'"}),
    t({"", ""}),
    t({"", "# ============================================"}),
    t({"", "# Prod (PLB) Environment Stages"}),
    t({"", "# ============================================"}),
    t({"", "- stage: PlanProd"}),
    t({"", "  displayName: 'Plan - PLB (Prod)'"}),
    t({"", "  dependsOn: DeployCanary"}),
    t({"", "  condition: succeeded()"}),
    t({"", "  jobs:"}),
    t({"", "  - job: PlanProdManagementGroups"}),
    t({"", "    displayName: 'Plan Management Groups - PLB'"}),
    t({"", "    steps:"}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionProd)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "            az account set --subscription $(subscriptionIdProd)"}),
    t({"", "            cd mgmt-group"}),
    t({"", ""}),
    t({"", "            # Get Azure context and set ARM variables for Azure provider authentication"}),
    t({"", "            SUBSCRIPTION_ID=$(az account show --query id -o tsv)"}),
    t({"", "            TENANT_ID=$(az account show --query tenantId -o tsv)"}),
    t({"", "            CLIENT_ID=$(az account show --query user.name -o tsv)"}),
    t({"", ""}),
    t({"", "            # Set ARM environment variables for Terraform Azure provider"}),
    t({"", "            export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID"}),
    t({"", "            export ARM_TENANT_ID=$TENANT_ID"}),
    t({"", "            export ARM_CLIENT_ID=$CLIENT_ID"}),
    t({"", "            export ARM_USE_OIDC=true"}),
    t({"", ""}),
    t({"", "            # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI"}),
    t({"", "            unset AZURE_CONFIG_DIR"}),
    t({"", "            "}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"Terraform Plan - PLB Production Environment\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID\""}),
    t({"", "            echo \"ARM_TENANT_ID: $ARM_TENANT_ID\""}),
    t({"", "            echo \"ARM_CLIENT_ID: $CLIENT_ID\""}),
    t({"", "            echo \"ARM_USE_OIDC: $ARM_USE_OIDC\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", ""}),
    t({"", "            terraform init \\"}),
    t({"", "              -backend-config=\"resource_group_name=$(backendResourceGroupProd)\" \\"}),
    t({"", "              -backend-config=\"storage_account_name=$(backendStorageAccountProd)\" \\"}),
    t({"", "              -backend-config=\"container_name=$(backendContainerName)\" \\"}),
    t({"", "              -backend-config=\"key=$(backendKeyPlb)\" \\"}),
    t({"", "              -var-file=plb.tfvars.json"}),
    t({"", ""}),
    t({"", "            terraform plan -var-file=plb.tfvars.json -out=tfplan-plb"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: true"}),
    t({"", "        displayName: 'Terraform Plan - PLB'"}),
    t({"", ""}),
    t({"", "- stage: DeployProd"}),
    t({"", "  displayName: 'Deploy - PLB (Prod)'"}),
    t({"", "  dependsOn: PlanProd"}),
    t({"", "  condition: succeeded()"}),
    t({"", "  jobs:"}),
    t({"", "  - job: DeployProdManagementGroups"}),
    t({"", "    displayName: 'Deploy Management Groups - PLB'"}),
    t({"", "    steps:"}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionProd)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "            az account set --subscription $(subscriptionIdProd)"}),
    t({"", "            cd mgmt-group"}),
    t({"", ""}),
    t({"", "            # Get Azure context and set ARM variables for Azure provider authentication"}),
    t({"", "            SUBSCRIPTION_ID=$(az account show --query id -o tsv)"}),
    t({"", "            TENANT_ID=$(az account show --query tenantId -o tsv)"}),
    t({"", "            CLIENT_ID=$(az account show --query user.name -o tsv)"}),
    t({"", ""}),
    t({"", "            # Set ARM environment variables for Terraform Azure provider"}),
    t({"", "            export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID"}),
    t({"", "            export ARM_TENANT_ID=$TENANT_ID"}),
    t({"", "            export ARM_CLIENT_ID=$CLIENT_ID"}),
    t({"", "            export ARM_USE_OIDC=true"}),
    t({"", ""}),
    t({"", "            # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI"}),
    t({"", "            unset AZURE_CONFIG_DIR"}),
    t({"", "            "}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"Terraform Apply - PLB Production Environment\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", "            echo \"ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID\""}),
    t({"", "            echo \"ARM_TENANT_ID: $ARM_TENANT_ID\""}),
    t({"", "            echo \"ARM_CLIENT_ID: $CLIENT_ID\""}),
    t({"", "            echo \"ARM_USE_OIDC: $ARM_USE_OIDC\""}),
    t({"", "            echo \"==========================================\""}),
    t({"", ""}),
    t({"", "            terraform init \\"}),
    t({"", "              -backend-config=\"resource_group_name=$(backendResourceGroupProd)\" \\"}),
    t({"", "              -backend-config=\"storage_account_name=$(backendStorageAccountProd)\" \\"}),
    t({"", "              -backend-config=\"container_name=$(backendContainerName)\" \\"}),
    t({"", "              -backend-config=\"key=$(backendKeyPlb)\" \\"}),
    t({"", "              -var-file=plb.tfvars.json"}),
    t({"", ""}),
    t({"", "            terraform apply -auto-approve -var-file=plb.tfvars.json -parallelism=50"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: true"}),
    t({"", "        displayName: 'Terraform Apply - PLB'"}),
    t({"", ""}),
  }),

  -- Trigger snippet with PowerShell tasks (full pipeline)
  s("trigger-pwsh-full-lua", {
    t({"trigger:"}),
    t({"", "  branches:"}),
    t({"", "    include:"}),
    t({"", "    - main"}),
    t({"", "  paths:"}),
    t({"", "    include:"}),
    t({"", "    - path/**"}),
    t({"", "  batch: true"}),
    t({"", ""}),
    t({"", "variables:"}),
    t({"", "  serviceConnectionDev: 'id-policy-vending-eus-dev-001'"}),
    t({"", "  serviceConnectionTest: 'id-policy-vending-eus-test-001'"}),
    t({"", "  serviceConnectionProd: 'id-policy-vending-eus-prod-001'"}),
    t({"", ""}),
    t({"", "pool: 'default'"}),
    t({"", ""}),
    t({"", "stages:"}),
    t({"", "- stage: Dev"}),
    t({"", "  displayName: Dev"}),
    t({"", "  jobs:"}),
    t({"", "  - job: DevJob"}),
    t({"", "    displayName: DevJob"}),
    t({"", ""}),
    t({"", "    steps: "}),
    t({"", "    - task: azurepowershell@5"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionDev)"}),
    t({"", "        scriptType: 'inlinescript' # 'filepath'"}),
    t({"", "        #scriptPath: '/script.ps1'"}),
    t({"", "        inline: |"}),
    t({"", "          echo \"Dev Deployment\""}),
    t({"", "          echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        #scriptArguments: '-param1 value1 -param2 value2'"}),
    t({"", "        errorActionPreference: 'stop' # 'continue' | 'silentlycontinue'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "        azurePowerShellVersion:  'latestversion' # 'otherversion'"}),
    t({"", "        #preferredAzurePowerShellVersion: '7.1.0'"}),
    t({"", "        pwsh: true"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    t({"", "- stage: Test"}),
    t({"", "  displayName: Test"}),
    t({"", "  jobs:"}),
    t({"", "  - job: TestJob"}),
    t({"", "    displayName: TestJob"}),
    t({"", ""}),
    t({"", "    steps: "}),
    t({"", "    - task: azurepowershell@5"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionTest)"}),
    t({"", "        scriptType: 'inlinescript' # 'filepath'"}),
    t({"", "        #scriptPath: '/script.ps1'"}),
    t({"", "        inline: |"}),
    t({"", "          echo \"Test Deployment\""}),
    t({"", "          echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        #scriptArguments: '-param1 value1 -param2 value2'"}),
    t({"", "        errorActionPreference: 'stop' # 'continue' | 'silentlycontinue'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "        azurePowerShellVersion:  'latestversion' # 'otherversion'"}),
    t({"", "        #preferredAzurePowerShellVersion: '7.1.0'"}),
    t({"", "        pwsh: true"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    t({"", "- stage: Prod"}),
    t({"", "  displayName: Prod"}),
    t({"", "  jobs:"}),
    t({"", "  - job: ProdJob"}),
    t({"", "    displayName: ProdJob"}),
    t({"", ""}),
    t({"", "    steps: "}),
    t({"", ""}),
    t({"", "    - task: azurepowershell@5"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionProd)"}),
    t({"", "        scriptType: 'inlinescript' # 'filepath'"}),
    t({"", "        #scriptPath: '/script.ps1'"}),
    t({"", "        inline: |"}),
    t({"", "          echo \"Prod Deployment\""}),
    t({"", "          echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        #scriptArguments: '-param1 value1 -param2 value2'"}),
    t({"", "        errorActionPreference: 'stop' # 'continue' | 'silentlycontinue'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "        azurePowerShellVersion:  'latestversion' # 'otherversion'"}),
    t({"", "        #preferredAzurePowerShellVersion: '7.1.0'"}),
    t({"", "        pwsh: true"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
  }),

  -- Stages snippet with AzureCLI@2 tasks
  s("stages-lua", {
    t({"stages:"}),
    t({"", "- stage: "}), i(1, "stage_name"),
    t({"", "  displayName: "}), i(2, "stage_name"),
    t({"", "  jobs:"}),
    t({"", "  - job: "}), i(3, "job_name"),
    t({"", "    displayName: "}), i(4, "job_name"),
    t({"", ""}),
    t({"", "    steps: "}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionDev)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "              echo \"Dev Deployment\""}),
    t({"", "              echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionTest)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "              echo \"Test Deployment\""}),
    t({"", "              echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    t({"", "    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: $(serviceConnectionProd)"}),
    t({"", "        scriptType: 'bash'"}),
    t({"", "        scriptLocation: 'inlineScript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "              echo \"Prod Deployment\""}),
    t({"", "              echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "      displayName: 'task displayname'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    i(0, ""),
  }),

  -- Step bash helloworld snippet
  s("step-bash-helloworld-lua", {
    t({"    steps: "}),
    t({"", "    - script: "}), i(1, "echo \"Hello World\""),
    t({"", "      displayName: \""}), i(2, "step-bash"), t({"\""}),
    t({"", ""}),
    i(0, ""),
  }),

  -- Step bash task snippet
  s("step-bash-task-lua", {
    t({"    - task: AzureCLI@2"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: '${"}), i(1, "serviceConnection"), t({"}'"}),
    t({"", "        scriptType: 'bash' # 'ps' | 'pscore' | 'batch'"}),
    t({"", "        scriptLocation: 'inlineScript' # 'scriptPath'"}),
    t({"", "        # scriptPath: '/pathtoscript'"}),
    t({"", "        inlineScript: |"}),
    t({"", "            az account set --subscription $(subscriptionIdDev)"}),
    t({"", "            cd policies/definitions/dev-plb-root"}),
    t({"", ""}),
    t({"", "            # Get Azure context and set ARM variables for Azure provider authentication"}),
    t({"", "            SUBSCRIPTION_ID=$(az account show --query id -o tsv)"}),
    t({"", "            TENANT_ID=$(az account show --query tenantId -o tsv)"}),
    t({"", "            CLIENT_ID=$(az account show --query user.name -o tsv)"}),
    t({"", ""}),
    t({"", "            # Set ARM environment variables for Terraform Azure provider"}),
    t({"", "            export ARM_SUBSCRIPTION_ID=$SUBSCRIPTION_ID"}),
    t({"", "            export ARM_TENANT_ID=$TENANT_ID"}),
    t({"", "            export ARM_CLIENT_ID=$CLIENT_ID"}),
    t({"", "            export ARM_USE_OIDC=true"}),
    t({"", ""}),
    t({"", "            # Unset Azure CLI config to force Terraform to use ARM variables instead of Azure CLI"}),
    t({"", "            unset AZURE_CONFIG_DIR"}),
    t({"", "            "}),
    t({"", "            echo \"ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID\""}),
    t({"", "            echo \"ARM_TENANT_ID: $ARM_TENANT_ID\""}),
    t({"", "            echo \"ARM_CLIENT_ID: $CLIENT_ID\""}),
    t({"", "            echo \"ARM_USE_OIDC: $ARM_USE_OIDC\""}),
    t({"", ""}),
    t({"", "            terraform init"}),
    t({"", "            # terraform force-unlock -force b92aa416-10c4-d4e5-b2ab-c9fc41c1ad87"}),
    t({"", "            terraform plan"}),
    t({"", "            "}), i(2, "echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""),
    t({"", "        #arguments: # string. Alias: scriptArguments. Script Arguments."}),
    t({"", "        # workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "        #failOnStandardError: false # boolean. Fail on Standard Error. Default: false."}),
    t({"", "      displayName: '"}), i(3, "task displayname"), t({"'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    i(0, ""),
  }),

  -- Step PowerShell task snippet
  s("step-pwsh-task-lua", {
    t({"    - task: azurepowershell@5"}),
    t({"", "      inputs:"}),
    t({"", "        azureSubscription: '${"}), i(1, "serviceConnection"), t({"}'"}),
    t({"", "        scriptType: 'inlinescript' # 'filepath'"}),
    t({"", "        #scriptPath: '/script.ps1'"}),
    t({"", "        inline: |"}),
    t({"", "          "}), i(2, "echo \"##vso[task.setvariable variable=varname;isoutput=true]varvalue\""),
    t({"", "        #scriptArguments: '-param1 value1 -param2 value2'"}),
    t({"", "        errorActionPreference: 'stop' # 'continue' | 'silentlycontinue'"}),
    t({"", "        failOnStandardError: false"}),
    t({"", "        azurePowerShellVersion:  'latestversion' # 'otherversion'"}),
    t({"", "        #preferredAzurePowerShellVersion: '7.1.0'"}),
    t({"", "        pwsh: true"}),
    t({"", "        workingDirectory: '$(System.DefaultWorkingDirectory)'"}),
    t({"", "      displayName: '"}), i(3, "task displayname"), t({"'"}),
    t({"", "      env:"}),
    t({"", "        KEY: $(VALUE)"}),
    t({"", ""}),
    i(0, ""),
  }),

  -- Step download artifact snippet
  s("step-download-artifact-lua", {
    t({"    - task: DownloadPipelineArtifact@2"}),
    t({"", "      inputs:"}),
    t({"", "        buildType: 'current'"}),
    t({"", "        artifactName: '"}), i(1, "artifactName"), t({"'"}),
    t({"", "        targetPath: '$(Pipeline.Workspace)' # path"}),
    t({"", ""}),
    i(0, ""),
  }),

  -- Step publish artifact snippet
  s("step-publish-artifact-lua", {
    t({"    - task: PublishPipelineArtifact@1"}),
    t({"", "      inputs:"}),
    t({"", "        targetPath: '$(System.DefaultWorkingDirectory)/"}), i(1, "pathtofile"), t({"'"}),
    t({"", "        artifact: '"}), i(2, "artifactName"), t({"'"}),
    t({"", "        publishLocation: 'pipeline' # 'filepath'"}),
    t({"", "      displayName: '"}), i(3, "taskName"), t({"'"}),
    t({"", ""}),
    i(0, ""),
  }),
})

