local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

-- ============================================================================
-- TERRAFORM SNIPPETS
-- ============================================================================

-- Terraform providers snippet
ls.add_snippets('terraform', {
  -- Terraform with Azure (AzureRM + AzAPI + Random)
  s("provider-azure-lua", {
    t({
      "terraform {",
      "  required_providers {",
      "    azapi = {",
      "      source  = \"Azure/azapi\"",
      "      version = \"~>2.0\"",
      "    }",
      "    azurerm = {",
      "      source  = \"hashicorp/azurerm\"",
      "      version = \"~>4.0\"",
      "    }",
      "    random = {",
      "      source  = \"hashicorp/random\"",
      "      version = \"~>3.0\"",
      "    }",
      "  }",
      "",
      "  backend \"azurerm\" {",
      "    resource_group_name  = \"rgname\"",
      "    storage_account_name = \"storageaccountname\"",
      "    container_name       = \"containername\"",
      "    key                  = \"terraform.tfstate\"",
      "  }",
      "}",
      "",
      "provider \"azurerm\" {",
      "  features {}",
      "  tenant_id       = \"tenantId\"",
      "  subscription_id = \"subscriptionId\"",
      "}",
      "",
      "provider \"azapi\" {",
      "  tenant_id       = \"tenantId\"",
      "  subscription_id = \"subscriptionId\"",
      "}",
      "",
      "provider \"random\" {",
      "}",
    }),
  }),

  -- Terraform variable snippet
  s("variable-lua", {
    t('variable "'),
    i(1, "id"),
    t({
      '" {',
      '  description = "',
    }),
    i(2, "The ID (name) of the management group"),
    t({
      '"',
      '  type        = ',
    }),
    i(3, "string"),
    t({
      '',
      '}',
    }),
    i(0),
  }),

  -- Terraform file function snippets
  s("file-lua", {
    i(1, "file"),
    t(" = file(\"${path.module}/"),
    i(2, "policy.json"),
    t("\")"),
    i(0),
  }),
  s("files-lua", {
    t({"  "}),
    i(1, "files"),
    t("      = fileset(path.module, \""),
    i(2, "**/*.json"),
    t({"\")", "  "}),
    i(3, "files_maps"),
    t(" = { for x in local."), i(4, "files"), t(" : \"${basename(dirname(\"${path.cwd}/${x}\"))}-${jsondecode(\"${file(x)}\").name}-${jsondecode(\"${file(x)}\").metadata.version}\" => jsondecode(file(x)) }"),
    i(0),
  }),
  s("current_folder-lua", {
    i(1, "current_folder"),
    t(" = path.cwd"),
    i(0),
  }),

  -- Terraform random provider snippets
  s("random-string-lua", {
    t({
      'resource "random_string" "',
    }),
    i(1, "example"),
    t({
      '" {',
      '  length  = ',
    }),
    i(2, "16"),
    t({
      '',
      '  special = ',
    }),
    i(3, "false"),
    t({
      '',
      '}',
    }),
    i(0),
  }),

  -- Terraform Azure Management Group snippet
  s("mg-lua", {
    t({
      'variable "first_hirarchy" {',
      '  description = "First hierarchy management groups."',
      '  type = object({',
      '    parent_id = string',
      '    management_groups = list(object({',
      '      id           = string',
      '      display_name = string',
      '    }))',
      '  })',
      '}',
      '',
      'variable "platform_hirarchy" {',
      '  description = "Platform hierarchy management groups."',
      '  type = object({',
      '    parent_id = string',
      '    management_groups = list(object({',
      '      id           = string',
      '      display_name = string',
      '    }))',
      '  })',
      '}',
      '',
      'variable "landing_zone_hirarchy" {',
      '  description = "Landing zone hierarchy management groups."',
      '  type = object({',
      '    parent_id = string',
      '    management_groups = list(object({',
      '      id           = string',
      '      display_name = string',
      '    }))',
      '  })',
      '}',
      '',
      'resource "azurerm_management_group" "first_hirarchy" {',
      '  for_each                   = { for mg in var.first_hirarchy.management_groups : mg.id => mg }',
      '  name                       = each.value.id',
      '  display_name               = each.value.display_name',
      '  parent_management_group_id = var.first_hirarchy.parent_id',
      '}',
      '',
      'resource "azurerm_management_group" "platform_hirarchy" {',
      '  for_each                   = { for mg in var.platform_hirarchy.management_groups : mg.id => mg }',
      '  name                       = each.value.id',
      '  display_name               = each.value.display_name',
      '  parent_management_group_id = var.platform_hirarchy.parent_id',
      '  depends_on                 = [azurerm_management_group.first_hirarchy]',
      '}',
      '',
      'resource "azurerm_management_group" "landing_zone_hirarchy" {',
      '  for_each                   = { for mg in var.landing_zone_hirarchy.management_groups : mg.id => mg }',
      '  name                       = each.value.id',
      '  display_name               = each.value.display_name',
      '  parent_management_group_id = var.landing_zone_hirarchy.parent_id',
      '  depends_on                 = [azurerm_management_group.first_hirarchy]',
      '}',
      '',
      'output "first_hirarchy_ids" {',
      '  description = "IDs of the first hierarchy management groups."',
      '  value       = azurerm_management_group.first_hirarchy',
      '}',
      '',
      'output "platform_hirarchy_ids" {',
      '  description = "IDs of the platform hierarchy management groups."',
      '  value       = azurerm_management_group.platform_hirarchy',
      '}',
      '',
      'output "landing_zone_hirarchy_ids" {',
      '  description = "IDs of the landing zone hierarchy management groups."',
      '  value       = azurerm_management_group.landing_zone_hirarchy',
      '}',
    }),
  }),

  -- Terraform Azure Policy Definition snippets
  s("policy-definition-lua", {
    t({
      'locals {',
      '  files      = fileset(path.module, "**/*.json")',
      '  files_maps = { for x in local.files : "${basename(dirname("${path.cwd}/${x}"))}/${jsondecode("${file(x)}").name}-${jsondecode("${file(x)}").metadata.version}" => jsondecode(file(x)) }',
      '}',
      '',
      'resource "azurerm_policy_definition" "definition" {',
      '  for_each            = local.files_maps',
      '  name                = each.value.name',
      '  policy_type         = each.value.policyType',
      '  mode                = each.value.mode',
      '  display_name        = each.value.displayName',
      '  description         = each.value.description',
      '  metadata            = jsonencode(each.value.metadata)',
      '  parameters          = jsonencode(each.value.parameters)',
      '  policy_rule         = jsonencode(each.value.policyRule)',
      '  management_group_id = "/providers/Microsoft.Management/managementGroups/${split("/", each.key)[0]}"',
      '}',
      '',
      'output "policy_definitions" {',
      '  description = "Map of all policy definitions created."',
      '  value       = azurerm_policy_definition.definition',
      '}',
    }),
  }),
  s("policy-initiative-lua", {
    t({
      'locals {',
      '  files      = fileset(path.module, "**/*.json")',
      '  files_maps = { for x in local.files : "${basename(dirname("${path.cwd}/${x}"))}/${jsondecode("${file(x)}").name}-${jsondecode("${file(x)}").metadata.version}" => jsondecode(file(x)) }',
      '}',
      '',
      'resource "azurerm_management_group_policy_set_definition" "initiative" {',
      '  for_each            = local.files_maps',
      '  name                = each.value.name',
      '  description         = each.value.description',
      '  metadata            = jsonencode(each.value.metadata)',
      '  policy_type         = each.value.policyType',
      '  display_name        = each.value.displayName',
      '  parameters          = jsonencode(each.value.parameters)',
      '  management_group_id = "/providers/Microsoft.Management/managementGroups/${split("/", each.key)[0]}"',
      '',
      '  dynamic "policy_definition_reference" {',
      '    for_each = each.value.policyDefinitionReference != null ? each.value.policyDefinitionReference : []',
      '    content {',
      '      policy_definition_id = policy_definition_reference.value.policyDefinitionId',
      '      parameter_values     = try(policy_definition_reference.value.parameterValues, null) != null ? jsonencode(policy_definition_reference.value.parameterValues) : null',
      '      reference_id         = try(policy_definition_reference.value.referenceId, null)',
      '    }',
      '  }',
      '',
      '  dynamic "policy_definition_group" {',
      '    for_each = each.value.policyDefinitionGroup != null ? each.value.policyDefinitionGroup : []',
      '    content {',
      '      name                            = policy_definition_group.value.name',
      '      display_name                    = try(policy_definition_group.value.displayName, null)',
      '      category                        = try(policy_definition_group.value.category, null)',
      '      description                     = try(policy_definition_group.value.description, null)',
      '      additional_metadata_resource_id = try(policy_definition_group.value.additionalMetadataResourceId, null)',
      '    }',
      '  }',
      '}',
      '',
      'output "policy_initiatives" {',
      '  description = "Map of all policy initiatives created."',
      '  value       = azurerm_management_group_policy_set_definition.initiative',
      '}',
    }),
  }),
})

-- ============================================================================
-- JSON SNIPPETS (for policy and management group JSON files)
-- ============================================================================

-- Policy Initiative JSON snippet
ls.add_snippets('json', {
  s("policy-initiative-json-lua", {
    t({
      '{',
      '  "name": "MCFLocations",',
      '  "policyType": "Custom",',
      '  "displayName": "MCF Allowed Locations Initiative",',
      '  "description": "Policy initiative to restrict resource creation to specified Azure regions for MCF control.",',
      '  "metadata": {',
      '    "version": "1.1.1",',
      '    "category": "General",',
      '    "owner": "sunny.bharne@gmail.com",',
      '    "control": "MCF"',
      '  },',
      '  "parameters": {',
      '    "allowedLocations": {',
      '      "type": "Array",',
      '      "metadata": {',
      '        "displayName": "Allowed Locations",',
      '        "description": "The list of locations allowed for resources."',
      '      },',
      '      "defaultValue": ["eastus"]',
      '    }',
      '  },',
      '  "policyDefinitionReference": [',
      '    {',
      '      "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/plb-canary/providers/Microsoft.Authorization/policyDefinitions/AllowedLocation",',
      '      "parameterValues": {',
      '        "allowedLocations": {',
      '          "value": "[parameters(\'allowedLocations\')]"',
      '        }',
      '      },',
      '      "referenceId": "AllowedLocationRef"',
      '    }',
      '  ],',
      '  "policyDefinitionGroup": [',
      '    {',
      '      "name": "LocationRestrictions",',
      '      "displayName": "Location Restrictions",',
      '      "category": "General",',
      '      "description": "Policies that restrict resource locations"',
      '    }',
      '  ]',
      '}',
    }),
  }),
  s("policy-definition-json-lua", {
    t({
      '{',
      '  "name": "AllowedLocation",',
      '  "policyType": "Custom",',
      '  "mode": "All",',
      '  "displayName": "Restrict Resource Location",',
      '  "description": "Restricts resource creation to specified Azure regions.",',
      '  "metadata": {',
      '    "version": "1.1.1",',
      '    "category": "General",',
      '    "owner": "sunny.bharne@gmail.com",',
      '    "control": "MCF"',
      '  },',
      '  "policyRule": {',
      '    "if": {',
      '      "not": {',
      '        "field": "location",',
      '        "in": "[parameters(\'allowedLocations\')]"',
      '      }',
      '    },',
      '    "then": {',
      '      "effect": "deny"',
      '    }',
      '  },',
      '  "parameters": {',
      '    "allowedLocations": {',
      '      "type": "Array",',
      '      "metadata": {',
      '        "displayName": "Allowed Locations",',
      '        "description": "The list of locations allowed for resources."',
      '      },',
      '      "defaultValue": ["eastus"]',
      '    }',
      '  }',
      '}',
    }),
  }),
  s("mg-json-lua", {
    t({
      '{',
      '  "first_hirarchy": {',
      '    "parent_id": "plb",',
      '    "management_groups": [',
      '      {',
      '        "id": "plb-platform",',
      '        "display_name": "Platform"',
      '      },',
      '      {',
      '        "id": "plb-landing-zones",',
      '        "display_name": "Landing Zones"',
      '      },',
      '      {',
      '        "id": "plb-decommissioned",',
      '        "display_name": "Decommissioned"',
      '      },',
      '      {',
      '        "id": "plb-sandbox",',
      '        "display_name": "Sandbox"',
      '      }',
      '    ]',
      '  },',
      '  "platform_hirarchy": {',
      '    "parent_id": "plb-platform",',
      '    "management_groups": [',
      '      {',
      '        "id": "plb-platform-security",',
      '        "display_name": "Security"',
      '      },',
      '      {',
      '        "id": "plb-platform-management",',
      '        "display_name": "Management"',
      '      },',
      '      {',
      '        "id": "plb-platform-identity",',
      '        "display_name": "Identity"',
      '      },',
      '      {',
      '        "id": "plb-platform-connectivity",',
      '        "display_name": "Connectivity"',
      '      }',
      '    ]',
      '  },',
      '  "landing_zone_hirarchy": {',
      '    "parent_id": "plb-landing-zones",',
      '    "management_groups": [',
      '      {',
      '        "id": "plb-landing-zones-corp",',
      '        "display_name": "Corp"',
      '      },',
      '      {',
      '        "id": "plb-landing-zones-online",',
      '        "display_name": "Online"',
      '      }',
      '    ]',
      '  }',
      '}',
    }),
  }),
  s("mg-json-canary-lua", {
    t({
      '{',
      '  "first_hirarchy": {',
      '    "parent_id": "plb-canary",',
      '    "management_groups": [',
      '      {',
      '        "id": "platform-canary",',
      '        "display_name": "Platform - Canary"',
      '      },',
      '      {',
      '        "id": "landing-zones-canary",',
      '        "display_name": "Landing Zones - Canary"',
      '      },',
      '      {',
      '        "id": "decommissioned-canary",',
      '        "display_name": "Decommissioned - Canary"',
      '      },',
      '      {',
      '        "id": "sandbox-canary",',
      '        "display_name": "Sandbox - Canary"',
      '      }',
      '    ]',
      '  },',
      '  "platform_hirarchy": {',
      '    "parent_id": "platform-canary",',
      '    "management_groups": [',
      '      {',
      '        "id": "platform-security-canary",',
      '        "display_name": "Security - Canary"',
      '      },',
      '      {',
      '        "id": "platform-management-canary",',
      '        "display_name": "Management - Canary"',
      '      },',
      '      {',
      '        "id": "platform-identity-canary",',
      '        "display_name": "Identity - Canary"',
      '      },',
      '      {',
      '        "id": "platform-connectivity-canary",',
      '        "display_name": "Connectivity - Canary"',
      '      }',
      '    ]',
      '  },',
      '  "landing_zone_hirarchy": {',
      '    "parent_id": "landing-zones-canary",',
      '    "management_groups": [',
      '      {',
      '        "id": "landing-zones-corp-canary",',
      '        "display_name": "Corp - Canary"',
      '      },',
      '      {',
      '        "id": "landing-zones-online-canary",',
      '        "display_name": "Online - Canary"',
      '      }',
      '    ]',
      '  }',
      '}',
    }),
  }),
})

